language.Add("Undone_e2_spawned_prop", "E2 Spawned Prop")
E2Helper.Descriptions["propManipulate"] = "Allows to do any single prop core function in one term.\n(position, rotation, freeze, gravity, notsolid)"
E2Helper.Descriptions["propSpawn"] = "Use the model string or a template entity to spawn a prop.\nYou can set the position and/or the rotation as well.\nThe last number indicates frozen/unfrozen."
E2Helper.Descriptions["propDelete"] = "Removes the given entity(s). Returns how may are deleted."
E2Helper.Descriptions["propFreeze"] = "Passing 0 unfreezes the entity, everything else freezes it."
E2Helper.Descriptions["propNotSolid"] = "Passing 0 makes the entity solid, everything else makes it non-solid."
E2Helper.Descriptions["propGravity"] = "Passing 0 makes the entity weightless, everything else makes it weighty."
E2Helper.Descriptions["setPos"] = "Sets the position of an entity."
E2Helper.Descriptions["reposition"] = "Deprecated. Kept for backwards-compatibility."
E2Helper.Descriptions["setAng"] = "Set the rotation of an entity."
E2Helper.Descriptions["rerotate"] = "Deprecated. Kept for backwards-compatibility."
E2Helper.Descriptions["parentTo"] = "Parents one entity to another."
E2Helper.Descriptions["deparent"] = "Unparents an entity, so it moves freely again."
E2Helper.Descriptions["propBreak"] = "Breaks/Explodes breakable/explodable props (Usefull for Mines)."
E2Helper.Descriptions["propCanCreate"] = "Returns 1 when propSpawn() will successfully spawn a prop until the limit is reached."
