name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Embed version
        run: |
          echo ${GITHUB_SHA:0:7} > lua/wire/version.lua

      - uses: wiremod/gmod-upload@master
        with:
          id: 160250458
          changelog: "Deployment via Github to commit ${GITUB_SHA:0:7}"
        env:
          STEAM_USERNAME: ${{ secrets.WIRETEAM_WORKSHOP_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WIRETEAM_WORKSHOP_PASSWORD }}
