name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v10

      - name: Run gma packer
        run: |
          lua .github/workflows/gma.lua wiremod.gma

      - name: Upload to workshop
        uses: wiremod/workshop-upload@a02cec0c6bd79bd2a514787485d806ed44c295f1
        with:
          appId: 4000
          itemId: 160250458
          contentPath: "wiremod.gma"
          changelog: "Deployment via Github to latest changes"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}